CREATE TABLE RECIPIENTS (
    RECIPIENT_ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(24),
    LAST_NAME VARCHAR(24),
    UNPAID_FINES DECIMAL(6,2),
    PRIMARY KEY (RECIPIENT_ID)
);

CREATE TABLE BOOKS (
    BOOK_ID INT NOT NULL AUTO_INCREMENT,
    BOOK_ISBN VARCHAR(13) NOT NULL,
    BOOK_HOLDER INT,
    RETURN_DATE DATE,
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (BOOK_HOLDER) REFERENCES RECIPIENTS(RECIPIENT_ID)
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT NOT NULL AUTO_INCREMENT,
    RECIPIENT_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    TRANSACTION_TYPE VARCHAR(24),
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (RECIPIENT_ID) REFERENCES RECIPIENTS(RECIPIENT_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

CREATE TABLE AUTHORIZATION_STAFF (
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD CHAR(64) NOT NULL,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE AUTHORIZATION_STUDENTS (
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD CHAR(64) NOT NULL,
    PRIMARY KEY (USERNAME)
);
